# syntax=docker/dockerfile:1

FROM python:3.11.4-bookworm

RUN apt-get update && apt-get install -y nodejs npm

# RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash - apt-get install -y nodejs

ENV SUBWAY=0,1
ENV RAPID_TRANSIT=0,1,4
ENV COMMUTER_RAIL=2
ENV BUS=3
ENV FERRY=4
ENV ALL_ROUTES=0,1,2,3,4
ENV LIST_KEYS=SUBWAY,RAPID_TRANSIT,COMMUTER_RAIL,BUS,FERRY,ALL_ROUTES
ENV PYTHONPATH=/helper_functions:/gtfs_schedule:/gtfs_realtime:/gtfs_loader:

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade -r requirements.txt
COPY . .

RUN apt-get update && apt-get install -y tzdata
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone

# Install leaflet plugins
# RUN rmdir -p ./static/node_modules
RUN mkdir -p ./static/node_modules
RUN npm install --prefix ./static leaflet-fullscreen
RUN npm install --prefix ./static leaflet-realtime
RUN npm install --prefix ./static leaflet-search

CMD "./start.sh"
# CMD ["wait"]
