"""FUCK THIS SHIT"""

ENV_DICT = {
    "SUBWAY": "0,1",
    "RAPID_TRANSIT": "0,1,4",
    "COMMUTER_RAIL": "2",
    "BUS": "3",
    "FERRY": "4",
    "ALL_ROUTES": "0,1,2,3,4",
    "LIST_KEYS": "SUBWAY,RAPID_TRANSIT,COMMUTER_RAIL,BUS,FERRY,ALL_ROUTES",
}
