# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: [push, pull_request]

defaults:
  run:
    working-directory: static

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./static/package-lock.json"
      - run: npm install
      # - run: yarn
      # - run: npm install -g eslint
      # - run: eslint . --ext .js,.jsx,.ts,.tsx
      - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
